### ISSUE TITLE
Game Engine/Framework

### ISSUE THREAD

**Issue by NEET-FEET** [Anon86009/PhilosophyFightingGame#2]
What are you gonna use?

**Comment by Anon86009** [comment]
Probably Unity. I might consider Game Maker, and I am open to suggestions as I have not started development yet.

**Comment by tfw-no-gf** [comment]
how about godot

**Comment by tfw-no-gf** [comment]
how about godot

**Comment by tfw-no-gf** [comment]
how about godot

**Comment by NEET-FEET** [comment]
I also recommend Godot
